# Generated by Django 4.1.3 on 2024-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_pdf_servicedetail_archive_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='icon',
            field=models.CharField(default=1, max_length=100, verbose_name='Icon of service'),
            preserve_default=False,
        ),
    ]
