# Generated by Django 4.1.3 on 2024-10-12 18:17

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicedetail_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='archive_pdf',
            field=models.FileField(blank=True, null=True, upload_to=services.models.custom_upload_to, verbose_name='Catalog'),
        ),
    ]
