# Generated by Django 4.1.3 on 2024-10-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_address_profile_company_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.CharField(default=1, max_length=100, verbose_name='Full name of user'),
            preserve_default=False,
        ),
    ]
