# Generated by Django 4.1.3 on 2024-10-12 18:17

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of client')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of image')),
                ('image', models.ImageField(upload_to=portfolio.models.custom_upload_to, verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Gallery of projects',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.models.custom_upload_to, verbose_name='Descriptive image')),
                ('title', models.CharField(max_length=100, verbose_name='Project title')),
                ('description', models.TextField(verbose_name='Project description')),
                ('projectFinished', models.CharField(max_length=100, verbose_name='End date')),
                ('projectUrl', models.URLField(max_length=250, verbose_name='Project URL')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated date')),
                ('category', models.ManyToManyField(related_name='Categories', to='portfolio.category', verbose_name='Category of project')),
                ('client', models.ManyToManyField(related_name='Clientes', to='portfolio.client', verbose_name='Client')),
                ('gallery', models.ManyToManyField(related_name='Gallery', to='portfolio.image', verbose_name='Gallery of images')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
