# Generated by Django 4.1.3 on 2024-10-12 19:18

from django.db import migrations, models
import testimonials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('testimonial', models.CharField(max_length=250, verbose_name='Testimonial')),
                ('profession', models.CharField(max_length=50, verbose_name='Profession or office')),
                ('image', models.ImageField(blank=True, null=True, upload_to=testimonials.models.custom_upload_to, verbose_name='Profile Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
